### ISSUE TITLE
Get Last Published Entry 

### ISSUE THREAD

**Issue by thilinahat** [pupudu/queuep#13]
I would be better if we can get the last entry published to queue. Because i recently faced the requirement where the data I publish to the queue is derived from the data I published previously.

**Comment by pupudu** [comment]
The requested feature is implemented as an async method. 

From the queue object, you can do
    
    myQueue.getEntry(key).then(/*do something*/)

or from queuep directly

    queuep.getEntry(qId, key).then(/*do something*/)

Note that you can also use callbacks instead of promises by passing a callback function as an additional parameter.

**Comment by pupudu** [comment]
The requested feature is implemented as an async method. 

From the queue object, you can do
    
    myQueue.getEntry(key).then((entry)=>{/*do something*/})

or from queuep directly

    queuep.getEntry(qId, key).then((entry)=>{/*do something*/})

Notes:
1. The entry returned here is a "qp entry", not the "data" itself. To access the `data`, you need to access `entry.data` instead. The entry will have other stats such as skipped count.
2. You can also use callbacks instead of promises by passing a callback function as an additional parameter.
